### ISSUE TITLE
项目经理招募帖

### ISSUE THREAD

**Issue by tuhaihe** [Apache-Flink-Docs-ZH/Apache-Flink-Docs-ZH-translation#1]
翻译是一件很耗费精力的事情，个人精力有限，所以希望招募一名项目经理，我们一起推进翻译项目顺利落地。

项目经理主要职责：
 - 定期跟进翻译、校对进度，以提升翻译项目推进速度
 - 协调项目成员间的沟通
 - 有效管理虚拟翻译团队（如有必要，可建微信群，我会协助项目经理同学管理）

报名要求：
 - 有责任心，希望一以贯之，不能半途而废，否则很影响整个翻译项目
 - 时间稍微丰富些，协调跟进估计会很费时间，如果你时间稍微丰富最好啦
 - 丰富的项目管理经验，IT行业从业者，如果有团队管理经验最好

当然，满足上面的几个条件最好啦，希望能找到一块协作的同学。

如果觉得自己合适，留言吧，谢谢啦~

**Comment by shenshunhou** [comment]
我可以参加

**Comment by tuhaihe** [comment]
欢迎，加我微信咱们聊聊吧：LinuxNews :)

**Comment by sunjincheng121** [comment]
是否可以写一个认领流程(wiki)页面似乎不能编辑？

**Comment by tuhaihe** [comment]
O(∩_∩)O哈哈~还有其他同学想承担PM角色的话，欢迎留言~

**Comment by shunguo** [comment]
+1

**Comment by tuhaihe** [comment]
哈哈，上面同学都没有加我微信呀，目前已经有同学认领PM角色。
暂时关闭本Issue了.
