### ISSUE TITLE
翻译微信群：认领翻译章节的同学可入群

### ISSUE THREAD

**Issue by tuhaihe** [Apache-Flink-Docs-ZH/Apache-Flink-Docs-ZH-translation#2]
认领翻译章节的同学，可以加入下面微信群（入群请填写个人认领页面填写的GitHub昵称）：

<img src="https://img.alicdn.com/tfs/TB15pRERXXXXXXTXFXXXXXXXXXX-674-896.jpg">

**Comment by HuangZhenyang** [comment]
“群聊人数超过100人，只可通过群成员邀请进群”
怎么办？

**Comment by tuhaihe** [comment]
@HuangZhenyang 可以单独加我的微信：LinuxNews 
我把你拉到群里

**Comment by wilsonlee626** [comment]
认领校对的有群吗？

**Comment by tuhaihe** [comment]
@wilsonlee626 有群，先加我吧~

**Comment by tuhaihe** [comment]
目前认领已满，临时关闭招募。
